apiVersion: v1
kind: Service
metadata:
  name: consul-2
  labels:
    name: consul-2
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8500
      targetPort: 8500
  selector:
    app: consul
